version: '3'
services:
    vue_wspollokator_app:
        restart: always
        container_name: vue_wspollokator_app
        image: vue_wspollokator_app
        build:
            context: ./
            dockerfile: $PWD/docker/dev/Dockerfile
        volumes:
            - ./:/home/node/vue-wspollokator-app
        ports:
            - 3000:5000