version: '3'
services:
    vue_wspollokator_app:
        restart: always
        container_name: vue_wspollokator_app
        image: vue_wspollokator_app
        build:
            context: ./
            dockerfile: $PWD/docker/prod/Dockerfile
        volumes:
            - ./:/app
        ports:
            - 3000:80